FROM node:20-alpine

WORKDIR /app

# Install dependencies first to cache this layer
COPY package.json package-lock.json* ./
RUN npm install

# We don't copy the source code here because it will be mounted as a volume
# in docker-compose.dev.yml to allow for hot-reloading!
